### PR TITLE
Modify statistics popup

### LINKED ISSUE #2146: Incorrect data in "critical signals" pie chart in statistics popup
**Context**

It seems that there is some discrepancy between the number of highly critical licenses shown in the "Critical Signals" piechart in Statistics Popup and in the “Criticality Bar” shown in the top bar.

**How to reproduce**

* Open `output_opossum.json` example file
* checkout the number of highly critical signals in the "Critical Signals" piechart in the Statistics Popup (0)
* navigate to audit view and switch to the criticality bar
* checkout the number of highly critical signals in the criticality bar (311)

In this example it can be seen that there are no highly critical signals in the piechart while there are highly critical signals in the criticality bar:

Screenshot 2023-10-11 at 18 12 51
Screenshot 2023-10-11 at 18 13 54

**Definition of Done**

The cause for this difference is identified and if necessary fixed.

### PR DESCRIPTION
**Pull request by vasily-pozdnyakov**
### Summary of changes

* Merged signals should be counted as one item at the project statistics popup
* Use "Signals Count" instead of "Count"
* Rename "Critical signals" to "Signals by criticality" and the pie chart legend
* Modify the heuristics to take the highest criticality at the statistics when there are license variants with different criticalities (here we take the risk of false-critical signals). At the end, colors at the "Critical signals" pie chart should agree with colors at Criticality Progress bar

### Context and reason for change

Fix #2146

### How can the changes be tested

See unit tests.
Open any example file and see the changes at Project Statistics popup. (see opossum_input file below)

**Before**
image

**After**
image

### CODE REVIEW

File: src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx [hunk 1]
```diff
@@ -17,11 +17,16 @@ import { ProjectLicensesTable } from '../ProjectLicensesTable/ProjectLicensesTab
 
 const LICENSE_COLUMN_NAME_IN_TABLE = 'License name';
 const COUNT_COLUMN_NAME_IN_TABLE = 'Count';
```
Comment (mstykow) [inline src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx:19]: what is the reason we need to keep the old "Count" column name? it seems that if you also adjust line 113 to use the new value, there is no need to introduce two different names for the same column.

File: src/Frontend/Components/AccordionWithPieChart/__tests__/accordion-with-pie-chart-helpers.test.tsx [hunk 2]
```diff
@@ -16,11 +16,11 @@ describe('getColorsForPieChart', () => {
     ];
     const criticalSignalsCount: Array<PieChartData> = [
       {
-        name: 'High',
+        name: 'Highly critical signals',
```
Comment (mstykow) [inline src/Frontend/Components/AccordionWithPieChart/__tests__/accordion-with-pie-chart-helpers.test.tsx:19]: please don't repeat user facing text in tests. instead, reference the enum you created.

File: src/Frontend/Components/ProjectStatisticsPopup/__tests__/ProjectStatisticsPopup.test.tsx [hunk 3]
```diff
@@ -201,7 +201,7 @@ describe('The ProjectStatisticsPopup', () => {
     renderComponentWithStore(<ProjectStatisticsPopup />, { store });
 
     expect(screen.getByText('Most Frequent Licenses')).toBeInTheDocument();
-    expect(screen.getByText('Critical Signals')).toBeInTheDocument();
+    expect(screen.getByText('Signals by Criticality')).toBeInTheDocument();
```
Comment (mstykow) [inline src/Frontend/Components/ProjectStatisticsPopup/__tests__/ProjectStatisticsPopup.test.tsx:204]: here too you can use the enum

File: src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx [hunk 4]
```diff
@@ -198,6 +213,16 @@ describe('getLicenseCriticality', () => {
 
     expect(licenseCriticality).toEqual(expectedLicenseCriticality);
   });
+
+  it('obtains the highest high criticality', () => {
```
Comment (mstykow) [inline src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx:217]: i don't see how this test is any different from the one that's called "obtains high criticality". i don't really see you testing something new and so i suggest you revert adding this test.

File: src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts [hunk 5]
```diff
@@ -173,28 +174,38 @@ export function getLicenseCriticality(licenseCriticalityCounts: {
...
       if (!uniqueLicenseNameToAttributions[strippedLicenseName]) {
         uniqueLicenseNameToAttributions[strippedLicenseName] = [];
       }
-      uniqueLicenseNameToAttributions[strippedLicenseName].push(attributionId);
+
+      if (!usedHashes.has(hash)) {
+        uniqueLicenseNameToAttributions[strippedLicenseName].push(
+          attributionId,
+        );
+        if (hash) {
```
Comment (mstykow) [inline src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts:205]: typescript says that `hash` is always a string because we haven't turned on the rule [noUncheckedIndexAccess](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) (this is a tech debt IMHO).

i think you're performing this check not because you're concerned about the empty string but because you know that `hash` could be undefined, correct?

but then it seems you should perform this null check before line 201 where you use `useHashes.has(hash)` which even has a risk of a null-pointer exception because `has` requires `hash` to always be a string.

**Review by mstykow — CHANGES_REQUESTED** [review]

File: src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx (hunk 1 above)
Comment (vasily-pozdnyakov) [reply src/Frontend/Components/CriticalLicensesTable/CriticalLicensesTable.tsx:19]: good point, you are right.

File: src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx (hunk 4 above)
Comment (vasily-pozdnyakov) [reply src/Frontend/Components/ProjectStatisticsPopup/__tests__/project-statistics-popup-helpers.test.tsx:217]: It was slightly different, but I get your point. Will delete it and slightly change "obtains high criticality" test.

File: src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts (hunk 5 above)
Comment (vasily-pozdnyakov) [reply src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts]: I made a refactoring here.

File: src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts [hunk 6]
```diff
@@ -173,27 +174,36 @@ export function getLicenseCriticality(licenseCriticalityCounts: {
...
-
     if (licenseName) {
       const strippedLicenseName = getStrippedLicenseName(licenseName);
-
       if (!uniqueLicenseNameToAttributions[strippedLicenseName]) {
         uniqueLicenseNameToAttributions[strippedLicenseName] = [];
       }
+
+      // We do not take into account duplicating (a.k.a merged) signals
+      if (attributionId in externalAttributionsToHashes) {
```
Comment (mstykow) [inline src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts:199]: this seen-check can and probably should be moved to the beginning of the for-loop.

File: src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts [hunk 7]
```diff
@@ -173,27 +174,36 @@ export function getLicenseCriticality(licenseCriticalityCounts: {
...
+    ? Criticality.Medium
     : undefined;
 }
 
 export function getUniqueLicenseNameToAttribution(
   attributions: Attributions,
+  externalAttributionsToHashes: AttributionsToHashes,
 ): UniqueLicenseNameToAttributions {
   const uniqueLicenseNameToAttributions: UniqueLicenseNameToAttributions = {};
+  const usedHashes: Set<string> = new Set<string>();
```
Comment (mstykow) [inline src/Frontend/Components/ProjectStatisticsPopup/project-statistics-popup-helpers.ts:189]: unnecessary type declaration

**Review by mstykow — APPROVED** [review]
