### PR TITLE
fix: fix pie charts legends being shown with the wrong colors

### LINKED ISSUE #2968: Wrong colors in statistics legends
**Describe the bug**
The colors in the statistics diagrams don't align with the mouseover.

**To Reproduce**

1. Open File
2. Go to `File > Project Statistics

**Expected behavior**
The legend entries show the same text as when you hover over the chart slice of the same color.

**Screenshots**

Image

Image

Image

**Desktop (please complete the following information):**

- OS: Ubuntu

### PR DESCRIPTION
**Pull request by LMayTNG**
### Summary of changes

Fix the colors of the pie charts legends in the project statistics

### Context and reason for change

Closes #2968

### CODE REVIEW

File: src/Frontend/Components/PieChart/PieChart.tsx [hunk 1]
```diff
@@ -80,7 +80,7 @@ export const PieChart: React.FC<PieChartProps> = (props) => {
             <div>
               {payload?.map((entry, index) => (
                 <div style={{ display: 'flex' }} key={`item-${index}`}>
-                  <div style={getLegendIconStyle(pieChartColors[index])} />
+                  <div style={getLegendIconStyle(entry.color ?? '')} />
```
Comment (mariusAsaTNG) [inline src/Frontend/Components/PieChart/PieChart.tsx]: Nice fix, however from a UI standpoint it looks better, when the list is sorted by color and not name. Hence, I would add a toSorted to payload. E.g.
```
.toSorted(
  (a, b) =>
    pieChartColors.indexOf(a.color ?? '') -
    pieChartColors.indexOf(b.color ?? ''),
)
```
This way the legend looks nice and is correct.

**Comment by Hellgartner** [comment]
Apart from the above, LGTM.

**Review by mariusAsaTNG — APPROVED** [review]
