### PR TITLE
Fix: Context menu does not check for disabled

### LINKED ISSUE #2016: Disabled triple dots in audit view are clickable
In Audit view, when no attribution is selected, the triple dots in the corner are greyed out and should be disabled. However, it is possible to click on them, and this opens up a context menu containing a disabled Undo button.

image
image

### PR DESCRIPTION
**Pull request by mstykow**
### Summary of changes

- add disabled check to ContextMenu
- add new unit tests and fix some integration tests that were failing as a result

### Context and reason for change

Closes #2016.

### How can the changes be tested

See task description: you won't be able to reproduce the bug anymore.

### CODE REVIEW

File: src/Frontend/test-helpers/attribution-column-test-helpers.ts [hunk 1]
```diff
@@ -54,10 +54,6 @@ export function expectButtonInHamburgerMenuIsNotShown(
   expect(
     screen.queryByRole('button', { name: buttonLabel }),
   ).not.toBeInTheDocument();
-
-  if (screen.queryByRole('presentation')) {
```
Comment (mstykow) [inline src/Frontend/test-helpers/attribution-column-test-helpers.ts:58]: a method named `expectButtonInHamburgerMenuIsNotShown` should not contain unrelated side-effects. these side-effects were causing other tests to fail.

File: src/Frontend/integration-tests/audit-view-tests/__tests__/audit-view.test.tsx [hunk 2]
```diff
@@ -174,6 +174,7 @@ describe('The App in Audit View', () => {
     clickOnValueInManualPackagePanelForParentAttribution(screen, 'React');
     expectValueInTextBox(screen, 'Name', 'React');
 
+    fireEvent.click(screen.getByRole('presentation').firstChild as Element);
```
Comment (mstykow) [inline src/Frontend/integration-tests/audit-view-tests/__tests__/audit-view.test.tsx:177]: only place where the side effect from `expectButtonInHamburgerMenuIsNotShown` was actually needed to clear the context menu.

File: src/Frontend/Components/ContextMenu/__tests__/ContextMenu.test.tsx [hunk 3]
```diff
@@ -145,4 +146,58 @@ describe('The ContextMenu', () => {
     fireEvent.click(screen.getByText(ButtonText.Save));
     expect(onCloseMock).toHaveBeenCalledTimes(1);
   });
+
+  it('is disabled when all menu items are disabled', () => {
+    // given
```
Comment (leslielazzarino) [inline src/Frontend/Components/ContextMenu/__tests__/ContextMenu.test.tsx:151]: As a convention, we do not write given/when/then. Exceptions are possible, but in this case I do no think that they make the tests easier to understand, as they are pretty short and simple already.

File: src/Frontend/Components/ContextMenu/__tests__/ContextMenu.test.tsx [hunk 4]
```diff
@@ -145,4 +146,58 @@ describe('The ContextMenu', () => {
...
+    const menuItem: ContextMenuItem = {
+      buttonText: ButtonText.Undo,
+      disabled: true,
+      onClick: noop,
+      hidden: false,
+    };
+    const trigger = 'Test Element';
```
Comment (leslielazzarino) [inline src/Frontend/Components/ContextMenu/__tests__/ContextMenu.test.tsx:158]: Why are you calling this "trigger"?

File: src/Frontend/integration-tests/audit-view-tests/__tests__/audit-view.test.tsx (hunk 2 above)
Comment (leslielazzarino) [reply src/Frontend/integration-tests/audit-view-tests/__tests__/audit-view.test.tsx:177]: I find this line quite obscure. Can we pack it in a function, whose name explains what we are doing?

**Review by leslielazzarino — CHANGES_REQUESTED** [review]

File: src/Frontend/integration-tests/audit-view-tests/__tests__/audit-view.test.tsx (hunk 2 above)
Comment (mstykow) [reply src/Frontend/integration-tests/audit-view-tests/__tests__/audit-view.test.tsx]: done

File: src/Frontend/Components/ContextMenu/__tests__/ContextMenu.test.tsx (hunk 3 above)
Comment (mstykow) [reply src/Frontend/Components/ContextMenu/__tests__/ContextMenu.test.tsx]: removed since such annotations are not commonly current practice

File: src/Frontend/Components/ContextMenu/__tests__/ContextMenu.test.tsx (hunk 4 above)
Comment (mstykow) [reply src/Frontend/Components/ContextMenu/__tests__/ContextMenu.test.tsx:157]: because this is the button label that, when clicked, triggers opening the menu. i find this more helpful as a variable name than "testElementText" which is what the other tests are using.

File: src/Frontend/test-helpers/context-menu-test-helpers.ts [hunk 5]
```diff
@@ -363,6 +363,10 @@ export function clickOnButtonInPackageContextMenu(
   fireEvent.click(button);
 }
 
+export function clearPopover(screen: Screen): void {
```
Comment (leslielazzarino) [inline src/Frontend/test-helpers/context-menu-test-helpers.ts:366]: nice

**Review by leslielazzarino — APPROVED** [review]
