### PR TITLE
fix: correctly display dates in project metadata popup

### LINKED ISSUE #2328: Dates not correctly displayed in project metadata popup
**Describe the bug**
Dates in the project metadata popup are not displayed in a user-friendly way:

**To Reproduce**
Open the project metadata popup on any opossum file.

**Expected behavior**
Display dates in a user-friendly way.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by mstykow**
### Summary of changes
- use dayjs to display dates in a user-friendly way
- extend list of expected attributes (automatically trying to parse all strings as dates may lead to false positives)

image

### Context and reason for change

Closes #2328.

### How can the changes be tested

Open the project metadata popup.

### CODE REVIEW

File: src/Frontend/Components/ProjectMetadataTable/ProjectMetadataTable.tsx [hunk 1]
```diff
@@ -36,44 +37,41 @@ export const projectMetadataTableClasses = {
...
-    );
-  }
-
   return (
     <MuiBox>
       <MuiTableContainer sx={projectMetadataTableClasses.container}>
         <MuiTable>
           <MuiTableBody>
-            {Object.keys(projectMetadata).map((key) => getTableRow(key))}
+            {Object.entries(projectMetadata).map(([key, value]) => (
```
Comment (leslielazzarino) [inline src/Frontend/Components/ProjectMetadataTable/ProjectMetadataTable.tsx:57]: I find such inline maps to html pretty  hard to read. Can we keep it extracted?

File: src/Frontend/Components/ProjectMetadataTable/ProjectMetadataTable.tsx [hunk 2]
```diff
@@ -36,44 +37,41 @@ export const projectMetadataTableClasses = {
...
+              <MuiTableRow key={key}>
+                <MuiTableCell sx={projectMetadataTableClasses.firstColumn}>
+                  {keyMetadata[key]?.title ?? key}
+                </MuiTableCell>
+                <MuiTableCell sx={projectMetadataTableClasses.secondColumn}>
+                  <pre>
+                    <MuiTypography fontFamily="default">
+                      {typeof value === 'string'
+                        ? keyMetadata[key]?.date
+                          ? dayjs(value).format('lll')
```
Comment (leslielazzarino) [inline src/Frontend/Components/ProjectMetadataTable/ProjectMetadataTable.tsx:67]: How this date format is defined is not explicit, it would be best to have a comment here, explaining what date format it corresponds to, i.e. MMMM D, YYYY h:mm A

**Review by leslielazzarino — CHANGES_REQUESTED** [review]

File: src/Frontend/Components/ProjectMetadataTable/ProjectMetadataTable.tsx (hunk 2 above)
Comment (mstykow) [reply src/Frontend/Components/ProjectMetadataTable/ProjectMetadataTable.tsx:67]: First, this is a localized date format and so there is no universal definition.
Second, repeating the definition as a comment almost defeats the purpose of using the shorthand. If somebody needs to know, they should look into the documentation. Also, if the library makes a change, I don't want to be updating all my comments.

File: src/Frontend/Components/ProjectMetadataTable/ProjectMetadataTable.tsx (hunk 1 above)
Comment (mstykow) [reply src/Frontend/Components/ProjectMetadataTable/ProjectMetadataTable.tsx:57]: Sure.

**Review by leslielazzarino — APPROVED** [review]
