### PR TITLE
fix: correct multiline textfield padding

### LINKED ISSUE #2530: Scroll bar in multi-line textfields is misaligned
**Describe the bug**
The scroll bar in multi-line textfields should be at the edge of the input field but is currently separated from this edge by some padding.

**To Reproduce**

Image

### PR DESCRIPTION
**Pull request by mstykow**
### Summary of changes

- move scroll bar to edge of input field and apply padding around input element instead

BEFORE:
image

AFTER:
image

### Context and reason for change

closes #2530

### How can the changes be tested

Check that both single and multiline textfields have the correct padding.

### CODE REVIEW

File: src/Frontend/Components/InputElements/TextBox.tsx [hunk 1]
```diff
@@ -33,24 +29,30 @@ export function TextBox(props: TextProps): ReactElement {
...
         disabled={!props.isEditable}
         error={props.error}
-        sx={textBoxSx}
+        sx={{
+          ...(props.isHighlighted ? highlightedStyling : {}),
+          ...inputElementClasses.textField,
+        }}
         label={props.title}
         InputProps={{
+          slotProps: {
```
Comment (alexzurbonsen) [inline src/Frontend/Components/InputElements/TextBox.tsx:43]: Seems logical and all works nicely. But I couldn't find this in the documentation (https://mui.com/material-ui/api/outlined-input/) Do you have a link for reference maybe?

File: src/Frontend/Components/InputElements/TextBox.tsx [hunk 2]
```diff
@@ -2,27 +2,23 @@
...
 import MuiInputAdornment from '@mui/material/InputAdornment';
 import MuiTextField from '@mui/material/TextField';
-import { ReactElement } from 'react';
 
 import { HighlightingColor } from '../../enums/enums';
-import { getSxFromPropsAndClasses } from '../../util/get-sx-from-props-and-classes';
 import { inputElementClasses, InputElementProps } from './shared';
 
 interface TextProps extends InputElementProps {
-  textFieldInputSx?: SxProps;
```
Comment (alexzurbonsen) [inline src/Frontend/Components/InputElements/TextBox.tsx:16]: This prop was unused?

File: src/Frontend/Components/InputElements/TextBox.tsx [hunk 3]
```diff
@@ -2,27 +2,23 @@
...
   minRows?: number;
   maxRows?: number;
-  endIcon?: ReactElement;
+  endIcon?: React.ReactElement;
```
Comment (alexzurbonsen) [inline src/Frontend/Components/InputElements/TextBox.tsx:15]: Why is it preferred to take these from a global namespace? My IDE complains mildly if I do this.

**Review by alexzurbonsen — APPROVED** [review]

File: src/Frontend/Components/InputElements/TextBox.tsx (hunk 2 above)
Comment (mstykow) [reply src/Frontend/Components/InputElements/TextBox.tsx:16]: yes

File: src/Frontend/Components/InputElements/TextBox.tsx (hunk 3 above)
Comment (mstykow) [reply src/Frontend/Components/InputElements/TextBox.tsx:15]: because it saves an import and thus also javascript lines of code. if the IDE is complaining, then it's not correctly configured to honor the global react namespace.

File: src/Frontend/Components/InputElements/TextBox.tsx (hunk 1 above)
Comment (mstykow) [reply src/Frontend/Components/InputElements/TextBox.tsx:43]: https://mui.com/material-ui/api/input/#input-prop-slotProps

File: src/Frontend/Components/InputElements/TextBox.tsx (hunk 3 above)
Comment (alexzurbonsen) [reply src/Frontend/Components/InputElements/TextBox.tsx:15]: With IDE is complaining I mean, that it is complaining about the usage of a global namespace. Apparently, it is configured to not appreciate that. It does recognize the variable though.

File: src/Frontend/Components/InputElements/TextBox.tsx (hunk 1 above)
Comment (alexzurbonsen) [reply src/Frontend/Components/InputElements/TextBox.tsx:43]: Thanks!
